const Map<String, String> enStrings = {
  "home": "Home",
  "about": "About",
  "services": "Services",
  "contact": "Contact",
  "downloadApps": "Get the app",
  "langBtn": "AR",
  'menu': 'Menu',
  'privacy_policy': 'Privacy Policy',
  'terms_conditions': 'Terms and conditions',

  "heroTitle": "Jaicom4\nOfficial App Website",
  "heroSubtitle":
  "An informational website for the Jaicom4 app.\nDownload for Android & iOS using the links below.",
  "tag1": "Professional",
  "tag2": "Simple",
  "tag3": "Fast",
  "btnAndroid": "Download Android",
  "btniOS": "Download iOS",

  "howTitle": "How it works",
  "howSub": "All operations happen inside the app.",
  "step1t": "Download",
  "step1s": "Android or iOS",
  "step2t": "Choose service",
  "step2s": "Plumber/Carpenter/Electrician/…",
  "step3t": "Request & connect",
  "step3s": "Everything is done inside the app",

  "profTitle": "Sample professions",
  "aboutTitle": "About us",
  "aboutSub": "Jaicom4 helps you reach the service you need professionally.",
  "bullet1": "This is a landing website for the app only.",
  "bullet2": "Requests and communication happen inside the app.",
  "bullet3": "Simple & fast experience.",

  "servicesTitle": "Our services",
  "servicesSub": "A quick overview of Jaicom4 value.",
  "s1t": "Easy access",
  "s1s": "Find the service you need quickly.",
  "s2t": "Clarity & trust",
  "s2s": "Clear info with a professional experience.",
  "s3t": "Support",
  "s3s": "Clear communication channels for inquiries.",

  "ctaTitle": "Ready to start?",
  "ctaSub": "Download the app for Android or iOS.",

  "contactTitle": "Contact us",
  "contactSub": "Send a message and we’ll get back to you.",
  "name": "Name",
  "phone": "Phone",
  "message": "Message",
  "send": "Send",
  "sent": "Message sent ✅",

  "svcHint": "Fast • Clear • Reliable",

  "fabContact": "Contact",
  "fabWhatsapp": "WhatsApp",
  "fabSnap": "Snapchat",
  "fabTiktok": "TikTok",
  "fabX": "X",

  "footer": "© Jaicom4 — Informational website, operations in-app",

  "aboutFastReachTitle": "Fast Reach",
  "aboutFastReachSub": "Nearby services",
  "aboutTrustedQualityTitle": "Trusted Quality",
  "aboutTrustedQualitySub": "Better selection",
  "aboutWiderVisionTitle": "Wider Vision",
  "aboutWiderVisionSub": "Built to scale",

  "email": "Email",
  "invalidValue": "invalid",
  "minPrefix": "min",
  "contactWhatsapp": "WhatsApp",
  "contactAddress": "Address",
  "contactAddressValue": "Riyadh, Saudi Arabia",

  "ctaFastAccess": "Fast access",
  "ctaTrustedServices": "Trusted services",
  "ctaBuiltToScale": "Built to scale",
  "ctaAvailableNow": "Available now",

  "heroBadge": "All-in-one services app",
  "heroHeadlineTop": "Your service\n",
  "heroHeadlineBottom": "one tap away",
  "heroDescription":
  "Download Jaycom4 and request any service easily — plumbing, electrical, carpentry & more.",
  "heroStatsSubtitle": "One app — all services",
  "heroStatServices": "Services",
  "heroStatUsers": "Users",
  "heroStatRating": "Rating",

  "servicesTagFast": "Fast",
  "servicesTagTrusted": "Trusted",
  "servicesTagSupport": "Support",
};