import 'app_lang.dart';

const Map<String, String> arStrings = {
  "home": "الرئيسية",
  "about": "من نحن",
  "services": "خدماتنا",
  "contact": "تواصل معنا",
  "downloadApps": "حمّل التطبيق",
  "langBtn": "EN",
  'menu': 'القائمة',
  "heroTitle": "Jaicom4\nالموقع الرسمي للتطبيق",
  "heroSubtitle":
  "منصة تعريفية لتطبيق Jaicom4.\nتحميل للأندرويد والآيفون من الروابط بالأسفل.",
  "tag1": "احترافية",
  "tag2": "سهولة",
  "tag3": "سرعة",
  "btnAndroid": "تحميل Android",
  "btniOS": "تحميل iOS",

  "howTitle": "كيف يعمل؟",
  "howSub": "التعامل الكامل يتم داخل التطبيق.",
  "step1t": "ثبت التطبيق",
  "step1s": "Android أو iOS",
  "step2t": "اختر الخدمة",
  "step2s": "سباك/نجار/كهربائي/…",
  "step3t": "تواصل واطلب",
  "step3s": "كل الشغل يتم من خلال التطبيق",

  "profTitle": "أمثلة للمهن",
  "aboutTitle": "من نحن",
  "aboutSub": "Jaicom4 يربطك بالخدمة التي تحتاجها بشكل احترافي.",
  "bullet1": "موقع تعريفي للتطبيق فقط.",
  "bullet2": "التواصل والطلبات تتم داخل التطبيق.",
  "bullet3": "تجربة بسيطة وسريعة.",

  "servicesTitle": "خدماتنا",
  "servicesSub": "لمحة عن قيمة Jaicom4.",
  "s1t": "سهولة الوصول",
  "s1s": "تلاقي الخدمة المطلوبة بسرعة.",
  "s2t": "وضوح وثقة",
  "s2s": "معلومات واضحة وتجربة احترافية.",
  "s3t": "دعم",
  "s3s": "قنوات تواصل واضحة لأي استفسار.",

  "ctaTitle": "جاهز تبدأ؟",
  "ctaSub": "حمّل التطبيق الآن للأندرويد أو الآيفون.",

  "contactTitle": "تواصل معنا",
  "contactSub": "ابعت رسالة وسنرد عليك.",
  "name": "الاسم",
  "phone": "رقم الجوال",
  "message": "رسالتك",
  "send": "إرسال",
  "sent": "تم إرسال رسالتك ✅",

  "fabContact": "تواصل",
  "fabWhatsapp": "واتساب",
  "fabSnap": "سناب",
  "fabTiktok": "تيكتوك",
  "fabX": "X",
  "svcHint": "سريع • واضح • موثوق",
  'privacy_policy': 'سياسة الخصوصية',
  'terms_conditions': 'الشروط والأحكام',
  "footer": "© Jaicom4 — الموقع تعريفي، التنفيذ داخل التطبيق",

  "aboutFastReachTitle": "وصول سريع",
  "aboutFastReachSub": "خدمات أقرب ليك",
  "aboutTrustedQualityTitle": "جودة موثوقة",
  "aboutTrustedQualitySub": "اختيار أسهل",
  "aboutWiderVisionTitle": "رؤية أوسع",
  "aboutWiderVisionSub": "جاهز للتوسع",

  "email": "البريد الإلكتروني",
  "invalidValue": "غير صالح",
  "minPrefix": "الحد الأدنى",
  "contactWhatsapp": "واتساب",
  "contactAddress": "العنوان",
  "contactAddressValue": "الرياض، المملكة العربية السعودية",

  "ctaFastAccess": "وصول أسرع",
  "ctaTrustedServices": "خدمات موثوقة",
  "ctaBuiltToScale": "جاهز للتوسع",
  "ctaAvailableNow": "متوفر الآن",

  "heroBadge": "تطبيق متكامل للخدمات",
  "heroHeadlineTop": "خدمتك\n",
  "heroHeadlineBottom": "على بُعد نقرة",
  "heroDescription":
  "حمّل Jaycom4 واطلب أي خدمة بسهولة — سباكة، كهرباء، نجارة وأكثر.",
  "heroStatsSubtitle": "تطبيق واحد — كل الخدمات",
  "heroStatServices": "خدمة",
  "heroStatUsers": "مستخدم",
  "heroStatRating": "تقييم",

  "servicesTagFast": "سريع",
  "servicesTagTrusted": "موثوق",
  "servicesTagSupport": "دعم",
};